# 1. Preparación del Entorno
* Asegúrate de tener instalado Pandas en tu entorno de trabajo.
* Descarga el archivo vgsales.csv desde Kaggle y colócalo en tu directorio de trabajo.
# 2. Cargar los Datos
* Carga el archivo vgsales.csv en un DataFrame de Pandas.
* Muestra las primeras 10 filas del DataFrame para confirmar que los datos se han cargado correctamente.

In [1]:
import pandas as pd

df=pd.read_csv("../data/vgsales.csv")

In [4]:
df.head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31

# 3. Exploración Inicial de los Datos
* Muestra las últimas 5 filas del DataFrame.
* Utiliza el método info() para obtener información general sobre el DataFrame, incluyendo el número de entradas, nombres de las columnas, tipos de datos y memoria utilizada.
* Genera estadísticas descriptivas del DataFrame utilizando el método describe().

In [5]:
df.tail(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [7]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

# 4. Inspección de los Datos
* Inspecciona los tipos de datos de cada columna utilizando el atributo dtypes.
* Cuenta los valores únicos en la columna Genre utilizando el método value_counts().
* Muestra todos los valores únicos en la columna Platform utilizando el método unique().

In [8]:
df.dtypes

Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [9]:
df['Genre'].value_counts()

Genre
Action          3316
Sports          2346
Misc            1739
Role-Playing    1488
Shooter         1310
Adventure       1286
Racing          1249
Platform         886
Simulation       867
Fighting         848
Strategy         681
Puzzle           582
Name: count, dtype: int64

In [10]:
df['Platform'].unique()

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne', 'GC',
       'WiiU', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

# 5. Filtrado de Datos
* Filtra el DataFrame para mostrar solo las filas donde las ventas en América del Norte (NA_Sales) sean mayores a 1 millón.
* Filtra el DataFrame para mostrar solo las filas donde las ventas en Japón (JP_Sales) sean menores a 0.1 millón.
* Utilizando el método query(), filtra el DataFrame para mostrar las filas donde el género sea Action y las ventas globales (Global_Sales) sean mayores a 2 millones.

In [12]:
df[df['NA_Sales'] > 1].sort_values(by='NA_Sales', ascending=False)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
...,...,...,...,...,...,...,...,...,...,...,...
471,472,Middle-Earth: Shadow of Mordor,PS4,2014.0,Action,Warner Bros. Interactive Entertainment,1.01,1.41,0.05,0.53,2.99
1954,1956,NFL Quarterback Club 98,N64,1997.0,Sports,Acclaim Entertainment,1.01,0.05,0.00,0.01,1.06
1917,1919,NCAA Football 14,X360,2013.0,Sports,Electronic Arts,1.01,0.00,0.00,0.06,1.07
1905,1907,Joust,2600,1982.0,Platform,Atari,1.01,0.06,0.00,0.01,1.08
1801,1803,MechAssault,XB,2002.0,Simulation,Microsoft Game Studios,1.01,0.10,0.00,0.03,1.13

In [14]:
df[df['JP_Sales'] <0.1].sort_values(by='JP_Sales')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16588,16591,Mega Brain Boost,DS,2008.0,Puzzle,Majesco Entertainment,0.01,0.00,0.00,0.00,0.01
16586,16589,Secret Files 2: Puritas Cordis,DS,2009.0,Adventure,Deep Silver,0.00,0.01,0.00,0.00,0.01
16585,16588,Breach,PC,2011.0,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01
16584,16587,Bust-A-Move 3000,GC,2003.0,Puzzle,Ubisoft,0.01,0.00,0.00,0.00,0.01
16583,16586,Carmageddon 64,N64,1999.0,Action,Virgin Interactive,0.01,0.00,0.00,0.00,0.01
...,...,...,...,...,...,...,...,...,...,...,...
7537,7539,Fairy Fencer F,PS3,2013.0,Role-Playing,Nippon Ichi Software,0.05,0.05,0.09,0.02,0.20
8374,8376,Beat Down: Fists of Vengeance,PS2,2005.0,Action,Capcom,0.04,0.03,0.09,0.01,0.17
7685,7687,Armored Core 4,PS3,2006.0,Simulation,505 Games,0.09,0.00,0.09,0.01,0.20
3561,3563,Odin Sphere,PS2,2007.0,Role-Playing,Square Enix,0.23,0.18,0.09,0.06,0.56
2354,2356,Mega Man 8 Anniversary Collector's Edition,PS,1996.0,Platform,Capcom,0.44,0.30,0.09,0.06,0.88

In [15]:
df.query("Genre == 'Action' and Global_Sales > 2").sort_values(by='Global_Sales', ascending=False)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
23,24,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
24,25,Grand Theft Auto: Vice City,PS2,2002.0,Action,Take-Two Interactive,8.41,5.49,0.47,1.78,16.15
38,39,Grand Theft Auto III,PS2,2001.0,Action,Take-Two Interactive,6.99,4.51,0.30,1.30,13.10
...,...,...,...,...,...,...,...,...,...,...,...
815,817,Tom Clancy's Splinter Cell: Conviction,X360,2010.0,Action,Ubisoft,1.20,0.63,0.04,0.19,2.06
817,819,The Incredibles,GBA,2004.0,Action,THQ,1.15,0.77,0.04,0.10,2.06
833,835,Peter Jackson's King Kong: The Official Game o...,PS2,2005.0,Action,Ubisoft,0.71,1.02,0.00,0.31,2.04
835,837,Need for Speed: The Run,PS3,2011.0,Action,Electronic Arts,0.58,1.06,0.03,0.37,2.04
840,842,Dead Space,PS3,2008.0,Action,Electronic Arts,1.05,0.67,0.00,0.30,2.02

# 6. Slicing de Datos
* Selecciona y muestra solo las columnas Name y Global_Sales del DataFrame.
* Utilizando loc[], selecciona y muestra las filas de la 5 a la 10 (inclusive) y las columnas Name y Genre.
* Utilizando iloc[], selecciona y muestra las primeras 5 filas y las primeras 3 columnas del DataFrame.

In [19]:
df[['Name', 'Global_Sales']]

                                                   Name  Global_Sales
0                                            Wii Sports         82.74
1                                     Super Mario Bros.         40.24
2                                        Mario Kart Wii         35.82
3                                     Wii Sports Resort         33.00
4                              Pokemon Red/Pokemon Blue         31.37
...                                                 ...           ...
16593                Woody Woodpecker in Crazy Castle 5          0.01
16594                     Men in Black II: Alien Escape          0.01
16595  SCORE International Baja 1000: The Official Game          0.01
16596                                        Know How 2          0.01
16597                                  Spirits & Spells          0.01

[16598 rows x 2 columns]

In [21]:
df.loc[5:10, ['Name', 'Genre']]

                         Name       Genre
5                      Tetris      Puzzle
6       New Super Mario Bros.    Platform
7                    Wii Play        Misc
8   New Super Mario Bros. Wii    Platform
9                   Duck Hunt     Shooter
10                 Nintendogs  Simulation

In [23]:
df.iloc[:5, 0:3]

   Rank                      Name Platform
0     1                Wii Sports      Wii
1     2         Super Mario Bros.      NES
2     3            Mario Kart Wii      Wii
3     4         Wii Sports Resort      Wii
4     5  Pokemon Red/Pokemon Blue       GB