# Analizando la Satisfacción de Clientes en la Industria Hotelera

Tu tarea es limpiar y explorar un dataset que contiene información sobre la satisfacción de los clientes en la industria hotelera. Este análisis es crucial para los ejecutivos de la empresa que buscan entender mejor las opiniones y experiencias de sus clientes para mejorar los servicios ofrecidos.

In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

df = pd.read_csv('../data/hotel_bookings.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [6]:
df.describe(include=[object])

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date
count,119390,119390,119390,118902,119390,119390,119390,119390,119390,119390,119390,119390
unique,2,12,5,177,8,5,10,12,3,4,3,926
top,City Hotel,August,BB,PRT,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2015-10-21
freq,79330,13877,92310,48590,56477,97870,85994,74053,104641,89613,75166,1461

In [5]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [22]:
df[df.duplicated(keep=False)]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
21,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07
39,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,No Deposit,250.0,NaN,0,Transient,137.00,0,1,Check-Out,2015-07-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119352,City Hotel,0,63,2017,August,35,31,0,3,3,...,No Deposit,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
119353,City Hotel,0,63,2017,August,35,31,0,3,3,...,No Deposit,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
119354,City Hotel,0,63,2017,August,35,31,0,3,3,...,No Deposit,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
119372,City Hotel,0,175,2017,August,35,31,1,3,1,...,No Deposit,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04
119373,City Hotel,0,175,2017,August,35,31,1,3,1,...,No Deposit,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04

In [7]:
datos_unicos = {col: df[col].unique() for col in df.columns}

In [8]:
datos_unicos

{'hotel': array(['Resort Hotel', 'City Hotel'], dtype=object),
 'is_canceled': array([0, 1]),
 'lead_time': array([342, 737,   7,  13,  14,   0,   9,  85,  75,  23,  35,  68,  18,
         37,  12,  72, 127,  78,  48,  60,  77,  99, 118,  95,  96,  69,
         45,  40,  15,  36,  43,  70,  16, 107,  47, 113,  90,  50,  93,
         76,   3,   1,  10,   5,  17,  51,  71,  63,  62, 101,   2,  81,
        368, 364, 324,  79,  21, 109, 102,   4,  98,  92,  26,  73, 115,
         86,  52,  29,  30,  33,  32,   8, 100,  44,  80,  97,  64,  39,
         34,  27,  82,  94, 110, 111,  84,  66, 104,  28, 258, 112,  65,
         67,  55,  88,  54, 292,  83, 105, 280, 394,  24, 103, 366, 249,
         22,  91,  11, 108, 106,  31,  87,  41, 304, 117,  59,  53,  58,
        116,  42, 321,  38,  56,  49, 317,   6,  57,  19,  25, 315, 123,
         46,  89,  61, 312, 299, 130,  74, 298, 119,  20, 286, 136, 129,
        124, 327, 131, 460, 140, 114, 139, 122, 137, 126, 120, 128, 135,
        150, 143, 151, 132, 125, 157, 147, 138, 156, 164, 346, 159, 160,
        161, 333, 381, 149, 154, 297, 163, 314, 155, 323, 340, 356, 142,
        328, 144, 336, 248, 302, 175, 344, 382, 146, 170, 166, 338, 167,
        310, 148, 165, 172, 171, 145, 121, 178, 305, 173, 152, 354, 347,
        158, 185, 349, 183, 352, 177, 200, 192, 361, 207, 174, 330, 134,
        350, 334, 283, 153, 197, 133, 241, 193, 235, 194, 261, 260, 216,
        169, 209, 238, 215, 141, 189, 187, 223, 284, 214, 202, 211, 168,
        230, 203, 188, 232, 709, 219, 162, 196, 190, 259, 228, 176, 250,
        201, 186, 199, 180, 206, 205, 224, 222, 182, 210, 275, 212, 229,
        218, 208, 191, 181, 179, 246, 255, 226, 288, 253, 252, 262, 236,
        256, 234, 254, 468, 213, 237, 198, 195, 239, 263, 265, 274, 217,
        220, 307, 221, 233, 257, 227, 276, 225, 264, 311, 277, 204, 290,
        266, 270, 294, 319, 282, 251, 322, 291, 269, 240, 271, 184, 231,
        268, 247, 273, 300, 301, 267, 244, 306, 293, 309, 272, 242, 295,
        285, 243, 308, 398, 303, 245, 424, 279, 331, 281, 339, 434, 357,
        325, 329, 278, 332, 343, 345, 360, 348, 367, 353, 373, 374, 406,
        400, 326, 379, 399, 316, 341, 320, 385, 355, 363, 358, 296, 422,
        390, 335, 370, 376, 375, 397, 289, 542, 403, 383, 384, 359, 393,
        337, 362, 365, 435, 386, 378, 313, 351, 287, 471, 462, 411, 450,
        318, 372, 371, 454, 532, 445, 389, 388, 407, 443, 437, 451, 391,
        405, 412, 419, 420, 426, 433, 440, 429, 418, 447, 461, 605, 457,
        475, 464, 482, 626, 489, 496, 503, 510, 517, 524, 531, 538, 545,
        552, 559, 566, 573, 580, 587, 594, 601, 608, 615, 622, 629, 396,
        410, 395, 423, 408, 409, 448, 465, 387, 414, 476, 479, 467, 490,
        493, 478, 504, 507, 458, 518, 521, 377, 444, 380, 463]),
 'arrival_date_year': array([2015, 2016, 2017]),
 'arrival_date_month': array(['July', 'August', 'September', 'October', 'November', 'December',
        'January', 'February', 'March', 'April', 'May', 'June'],
       dtype=object),
 'arrival_date_week_number': array([27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49, 50, 51, 52, 53,  1,  2,  3,  4,  5,  6,  7,
         8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
        25, 26]),
 'arrival_date_day_of_month': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]),
 'stays_in_weekend_nights': array([ 0,  1,  2,  4,  3,  6, 13,  8,  5,  7, 12,  9, 16, 18, 19, 10, 14]),
 'stays_in_week_nights': array([ 0,  1,  2,  3,  4,  5, 10, 11,  8,  6,  7, 15,  9, 12, 33, 20, 14,
        16, 21, 13, 30, 19, 24, 40, 22, 42, 50, 25, 17, 32, 26, 18, 34, 35,
        41]),
 'adults': array([ 2,  1,  3,  4, 40, 26, 50, 27, 55,  0, 20,  6,  5, 10]),
 'children': array([ 0.,  1.,  2., 10.,  3., nan]),
 'babies': array([ 0,  1,  2, 10,  9]),
 'meal': array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object),
 'country': array(['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA', nan, 'ROU', 'NOR', 'OMN',
        'ARG', 'POL', 'DEU', 'BEL', 'CHE', 'CN', 'GRC', 'ITA', 'NLD',
        'DNK', 'RUS', 'SWE', 'AUS', 'EST', 'CZE', 'BRA', 'FIN', 'MOZ',
        'BWA', 'LUX', 'SVN', 'ALB', 'IND', 'CHN', 'MEX', 'MAR', 'UKR',
        'SMR', 'LVA', 'PRI', 'SRB', 'CHL', 'AUT', 'BLR', 'LTU', 'TUR',
        'ZAF', 'AGO', 'ISR', 'CYM', 'ZMB', 'CPV', 'ZWE', 'DZA', 'KOR',
        'CRI', 'HUN', 'ARE', 'TUN', 'JAM', 'HRV', 'HKG', 'IRN', 'GEO',
        'AND', 'GIB', 'URY', 'JEY', 'CAF', 'CYP', 'COL', 'GGY', 'KWT',
        'NGA', 'MDV', 'VEN', 'SVK', 'FJI', 'KAZ', 'PAK', 'IDN', 'LBN',
        'PHL', 'SEN', 'SYC', 'AZE', 'BHR', 'NZL', 'THA', 'DOM', 'MKD',
        'MYS', 'ARM', 'JPN', 'LKA', 'CUB', 'CMR', 'BIH', 'MUS', 'COM',
        'SUR', 'UGA', 'BGR', 'CIV', 'JOR', 'SYR', 'SGP', 'BDI', 'SAU',
        'VNM', 'PLW', 'QAT', 'EGY', 'PER', 'MLT', 'MWI', 'ECU', 'MDG',
        'ISL', 'UZB', 'NPL', 'BHS', 'MAC', 'TGO', 'TWN', 'DJI', 'STP',
        'KNA', 'ETH', 'IRQ', 'HND', 'RWA', 'KHM', 'MCO', 'BGD', 'IMN',
        'TJK', 'NIC', 'BEN', 'VGB', 'TZA', 'GAB', 'GHA', 'TMP', 'GLP',
        'KEN', 'LIE', 'GNB', 'MNE', 'UMI', 'MYT', 'FRO', 'MMR', 'PAN',
        'BFA', 'LBY', 'MLI', 'NAM', 'BOL', 'PRY', 'BRB', 'ABW', 'AIA',
        'SLV', 'DMA', 'PYF', 'GUY', 'LCA', 'ATA', 'GTM', 'ASM', 'MRT',
        'NCL', 'KIR', 'SDN', 'ATF', 'SLE', 'LAO'], dtype=object),
 'market_segment': array(['Direct', 'Corporate', 'Online TA', 'Offline TA/TO',
        'Complementary', 'Groups', 'Undefined', 'Aviation'], dtype=object),
 'distribution_channel': array(['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS'], dtype=object),
 'is_repeated_guest': array([0, 1]),
 'previous_cancellations': array([ 0,  1,  2,  3, 26, 25, 14,  4, 24, 19,  5, 21,  6, 13, 11]),
 'previous_bookings_not_canceled': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 19, 26, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72]),
 'reserved_room_type': array(['C', 'A', 'D', 'E', 'G', 'F', 'H', 'L', 'P', 'B'], dtype=object),
 'assigned_room_type': array(['C', 'A', 'D', 'E', 'G', 'F', 'I', 'B', 'H', 'P', 'L', 'K'],
       dtype=object),
 'booking_changes': array([ 3,  4,  0,  1,  2,  5, 17,  6,  8,  7, 10, 16,  9, 13, 12, 20, 14,
        15, 11, 21, 18]),
 'deposit_type': array(['No Deposit', 'Refundable', 'Non Refund'], dtype=object),
 'agent': array([ nan, 304., 240., 303.,  15., 241.,   8., 250., 115.,   5., 175.,
        134., 156., 243., 242.,   3., 105.,  40., 147., 306., 184.,  96.,
          2., 127.,  95., 146.,   9., 177.,   6., 143., 244., 149., 167.,
        300., 171., 305.,  67., 196., 152., 142., 261., 104.,  36.,  26.,
         29., 258., 110.,  71., 181.,  88., 251., 275.,  69., 248., 208.,
        256., 314., 126., 281., 273., 253., 185., 330., 334., 328., 326.,
        321., 324., 313.,  38., 155.,  68., 335., 308., 332.,  94., 348.,
        310., 339., 375.,  66., 327., 387., 298.,  91., 245., 385., 257.,
        393., 168., 405., 249., 315.,  75., 128., 307.,  11., 436.,   1.,
        201., 183., 223., 368., 336., 291., 464., 411., 481.,  10., 154.,
        468., 410., 390., 440., 495., 492., 493., 434.,  57., 531., 420.,
        483., 526., 472., 429.,  16., 446.,  34.,  78., 139., 252., 270.,
         47., 114., 301., 193., 182., 135., 350., 195., 352., 355., 159.,
        363., 384., 360., 331., 367.,  64., 406., 163., 414., 333., 427.,
        431., 430., 426., 438., 433., 418., 441., 282., 432.,  72., 450.,
        180., 454., 455.,  59., 451., 254., 358., 469., 165., 467., 510.,
        337., 476., 502., 527., 479., 508., 535., 302., 497., 187.,  13.,
          7.,  27.,  14.,  22.,  17.,  28.,  42.,  20.,  19.,  45.,  37.,
         61.,  39.,  21.,  24.,  41.,  50.,  30.,  54.,  52.,  12.,  44.,
         31.,  83.,  32.,  63.,  60.,  55.,  56.,  89.,  87., 118.,  86.,
         85., 210., 214., 129., 179., 138., 174., 170., 153.,  93., 151.,
        119.,  35., 173.,  58.,  53., 133.,  79., 235., 192., 191., 236.,
        162., 215., 157., 287., 132., 234.,  98.,  77., 103., 107., 262.,
        220., 121., 205., 378.,  23., 296., 290., 229.,  33., 286., 276.,
        425., 484., 323., 403., 219., 394., 509., 111., 423.,   4.,  70.,
         82.,  81.,  74.,  92.,  99.,  90., 112., 117., 106., 148., 158.,
        144., 211., 213., 216., 232., 150., 267., 227., 247., 278., 280.,
        285., 289., 269., 295., 265., 288., 122., 294., 325., 341., 344.,
        346., 359., 283., 364., 370., 371.,  25., 141., 391., 397., 416.,
        404., 299., 197.,  73., 354., 444., 408., 461., 388., 453., 459.,
        474., 475., 480., 449.]),
 'company': array([ nan, 110., 113., 270., 178., 240., 154., 144., 307., 268.,  59.,
        204., 312., 318.,  94., 174., 274., 195., 223., 317., 281., 118.,
         53., 286.,  12.,  47., 324., 342., 373., 371., 383.,  86.,  82.,
        218.,  88.,  31., 397., 392., 405., 331., 367.,  20.,  83., 416.,
         51., 395., 102.,  34.,  84., 360., 394., 457., 382., 461., 478.,
        386., 112., 486., 421.,   9., 308., 135., 224., 504., 269., 356.,
        498., 390., 513., 203., 263., 477., 521., 169., 515., 445., 337.,
        251., 428., 292., 388., 130., 250., 355., 254., 543., 531., 528.,
         62., 120.,  42.,  81., 116., 530., 103.,  39.,  16.,  92.,  61.,
        501., 165., 291., 290.,  43., 325., 192., 108., 200., 465., 287.,
        297., 490., 482., 207., 282., 437., 225., 329., 272.,  28.,  77.,
        338.,  72., 246., 319., 146., 159., 380., 323., 511., 407., 278.,
         80., 403., 399.,  14., 137., 343., 346., 347., 349., 289., 351.,
        353.,  54.,  99., 358., 361., 362., 366., 372., 365., 277., 109.,
        377., 379.,  22., 378., 330., 364., 401., 232., 255., 384., 167.,
        212., 514., 391., 400., 376., 402., 396., 302., 398.,   6., 370.,
        369., 409., 168., 104., 408., 413., 148.,  10., 333., 419., 415.,
        424., 425., 423., 422., 435., 439., 442., 448., 443., 454., 444.,
         52., 459., 458., 456., 460., 447., 470., 466., 484., 184., 485.,
         32., 487., 491., 494., 193., 516., 496., 499.,  29.,  78., 520.,
        507., 506., 512., 126.,  64., 242., 518., 523., 539., 534., 436.,
        525., 541.,  40., 455., 410.,  45.,  38.,  49.,  48.,  67.,  68.,
         65.,  91.,  37.,   8., 179., 209., 219., 221., 227., 153., 186.,
        253., 202., 216., 275., 233., 280., 309., 321.,  93., 316.,  85.,
        107., 350., 279., 334., 348., 150.,  73., 385., 418., 197., 450.,
        452., 115.,  46.,  76.,  96., 100., 105., 101., 122.,  11., 139.,
        142., 127., 143., 140., 149., 163., 160., 180., 238., 183., 222.,
        185., 217., 215., 213., 237., 230., 234.,  35., 245., 158., 258.,
        259., 260., 411., 257., 271.,  18., 106., 210., 273.,  71., 284.,
        301., 305., 293., 264., 311., 304., 313., 288., 320., 314., 332.,
        341., 352., 243., 368., 393., 132., 220., 412., 420., 426., 417.,
        429., 433., 446., 357., 479., 483., 489., 229., 481., 497., 451.,
        492.]),
 'days_in_waiting_list': array([  0,  50,  47,  65, 122,  75, 101, 150, 125,  14,  60,  34, 100,
         22, 121,  61,  39,   5,   1,   8, 107,  43,  52,   2,  11, 142,
        116,  13,  44,  97,  83,   4, 113,  18,  20, 185,  93, 109,   6,
         37, 105, 154,  64,  99,  38,  48,  33,  77,  21,  80,  59,  40,
         58,  89,  53,  49,  69,  87,  91,  57, 111,  79,  98,  85,  63,
         15,   3,  41, 224,  31,  56, 187, 176,  71,  55,  96, 236, 259,
        207, 215, 160, 120,  30,  32,  27,  62,  24, 108, 147, 379,  70,
         35, 178, 330, 223, 174, 162, 391,  68, 193,  10,  76,  16,  28,
          9, 165,  17,  25,  46,   7,  84, 175, 183,  23, 117,  12,  54,
         26,  73,  45,  19,  42,  72,  81,  92,  74, 167,  36]),
 'customer_type': array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object),
 'adr': array([  0.  ,  75.  ,  98.  , ..., 266.75, 209.25, 157.71], shape=(8879,)),
 'required_car_parking_spaces': array([0, 1, 2, 8, 3]),
 'total_of_special_requests': array([0, 1, 3, 2, 4, 5]),
 'reservation_status': array(['Check-Out', 'Canceled', 'No-Show'], dtype=object),
 'reservation_status_date': array(['2015-07-01', '2015-07-02', '2015-07-03', '2015-05-06',
        '2015-04-22', '2015-06-23', '2015-07-05', '2015-07-06',
        '2015-07-07', '2015-07-08', '2015-05-11', '2015-07-15',
        '2015-07-16', '2015-05-29', '2015-05-19', '2015-06-19',
        '2015-05-23', '2015-05-18', '2015-07-09', '2015-06-02',
        '2015-07-13', '2015-07-04', '2015-06-29', '2015-06-16',
        '2015-06-18', '2015-06-12', '2015-06-09', '2015-05-26',
        '2015-07-11', '2015-07-12', '2015-07-17', '2015-04-15',
        '2015-05-13', '2015-07-10', '2015-05-20', '2015-05-12',
        '2015-07-14', '2015-06-17', '2015-05-01', '2015-03-30',
        '2015-07-19', '2015-06-03', '2015-06-26', '2015-05-14',
        '2015-07-20', '2015-05-07', '2015-05-28', '2015-04-13',
        '2015-03-25', '2015-07-21', '2015-06-27', '2015-07-18',
        '2015-07-23', '2015-06-08', '2015-06-22', '2015-06-24',
        '2015-03-05', '2015-06-01', '2015-04-24', '2015-07-22',
        '2015-05-27', '2015-04-06', '2015-04-11', '2015-07-25',
        '2015-07-28', '2015-07-29', '2015-06-25', '2015-07-24',
        '2015-06-05', '2015-06-30', '2015-06-13', '2015-06-11',
        '2015-07-30', '2015-07-27', '2015-04-29', '2015-06-04',
        '2015-07-26', '2015-08-01', '2015-08-02', '2015-06-15',
        '2015-04-23', '2015-07-31', '2015-05-25', '2015-08-03',
        '2015-04-17', '2015-08-04', '2015-08-06', '2015-05-15',
        '2015-05-09', '2015-03-17', '2015-05-22', '2015-08-07',
        '2015-04-04', '2015-08-05', '2015-08-08', '2015-08-10',
        '2015-05-04', '2015-06-06', '2015-08-09', '2015-08-15',
        '2015-08-11', '2015-03-28', '2015-08-14', '2015-08-12',
        '2015-08-16', '2015-05-16', '2015-08-21', '2015-08-13',
        '2015-08-17', '2015-04-20', '2015-08-18', '2015-08-23',
        '2015-08-22', '2015-08-19', '2015-08-20', '2015-08-29',
        '2015-03-31', '2015-05-30', '2015-08-25', '2015-04-14',
        '2015-08-24', '2015-03-24', '2015-05-21', '2015-08-28',
        '2015-08-26', '2015-08-27', '2015-08-30', '2015-08-31',
        '2015-09-06', '2015-09-03', '2015-09-04', '2015-09-02',
        '2015-09-01', '2015-09-05', '2015-06-20', '2015-09-07',
        '2015-09-10', '2015-09-11', '2015-09-08', '2015-09-09',
        '2015-09-13', '2015-09-15', '2015-04-10', '2015-01-02',
        '2014-11-18', '2015-09-12', '2015-09-17', '2015-09-14',
        '2015-04-07', '2015-09-19', '2015-09-16', '2015-09-20',
        '2015-01-18', '2015-10-23', '2015-01-22', '2015-01-01',
        '2015-09-22', '2015-09-24', '2015-09-18', '2015-09-21',
        '2015-09-30', '2015-09-25', '2015-09-27', '2015-09-28',
        '2015-10-12', '2015-09-29', '2015-09-23', '2015-10-01',
        '2015-09-26', '2015-04-18', '2015-10-02', '2015-10-04',
        '2015-10-08', '2015-10-03', '2015-10-07', '2015-10-09',
        '2015-10-11', '2015-10-05', '2015-10-06', '2015-10-10',
        '2015-10-14', '2015-10-15', '2015-10-18', '2015-10-13',
        '2015-10-20', '2015-10-19', '2015-10-31', '2015-10-16',
        '2015-10-21', '2015-10-22', '2015-10-17', '2015-10-24',
        '2015-10-25', '2015-10-28', '2015-10-27', '2015-10-26',
        '2015-10-30', '2015-11-05', '2015-10-29', '2015-11-03',
        '2015-11-07', '2015-11-04', '2015-11-01', '2015-11-02',
        '2015-11-17', '2015-11-06', '2015-11-10', '2015-11-08',
        '2015-11-09', '2015-11-15', '2015-11-16', '2015-11-11',
        '2015-11-12', '2015-11-14', '2015-11-13', '2015-11-18',
        '2015-11-22', '2015-11-19', '2015-11-21', '2015-11-20',
        '2015-11-24', '2015-11-25', '2015-11-23', '2015-11-28',
        '2015-11-26', '2015-11-27', '2015-11-29', '2015-12-04',
        '2015-12-01', '2015-12-06', '2015-12-08', '2015-12-02',
        '2015-12-03', '2015-12-31', '2015-12-05', '2015-12-10',
        '2015-12-17', '2015-11-30', '2015-12-12', '2015-12-07',
        '2016-01-05', '2015-12-11', '2015-12-13', '2015-12-15',
        '2015-12-16', '2015-12-19', '2015-12-18', '2015-12-26',
        '2015-12-27', '2015-12-22', '2015-12-23', '2015-12-24',
        '2015-12-29', '2015-12-28', '2015-12-20', '2015-12-30',
        '2016-01-02', '2016-01-01', '2015-12-25', '2016-01-03',
        '2016-01-04', '2016-01-11', '2016-01-07', '2015-12-21',
        '2016-01-09', '2016-01-10', '2016-01-08', '2016-01-06',
        '2016-01-12', '2016-01-13', '2016-01-23', '2016-02-09',
        '2016-01-15', '2016-01-16', '2016-01-17', '2016-01-19',
        '2016-01-18', '2016-01-21', '2016-01-24', '2016-01-22',
        '2016-01-29', '2016-01-27', '2016-01-25', '2016-03-08',
        '2016-01-26', '2016-01-20', '2016-01-30', '2016-02-01',
        '2016-02-02', '2016-02-08', '2016-02-07', '2016-01-28',
        '2016-02-05', '2016-02-03', '2016-02-13', '2016-02-10',
        '2016-02-04', '2016-02-12', '2016-02-11', '2016-02-16',
        '2016-02-14', '2016-02-15', '2016-02-20', '2016-02-06',
        '2016-01-14', '2016-02-17', '2016-02-21', '2016-02-24',
        '2016-02-25', '2016-02-19', '2016-02-18', '2016-02-26',
        '2016-02-23', '2016-03-05', '2016-02-22', '2016-02-27',
        '2016-03-03', '2016-03-24', '2016-03-04', '2016-02-29',
        '2016-03-01', '2016-03-02', '2016-03-30', '2016-03-07',
        '2016-03-14', '2016-03-21', '2016-03-09', '2016-03-12',
        '2016-03-22', '2016-03-10', '2016-03-11', '2016-03-20',
        '2016-03-15', '2016-03-17', '2016-03-16', '2016-03-19',
        '2016-03-27', '2016-03-18', '2016-03-26', '2016-03-31',
        '2016-03-28', '2016-03-29', '2016-04-01', '2016-03-23',
        '2016-04-02', '2016-03-25', '2016-03-13', '2016-04-04',
        '2016-04-03', '2016-04-05', '2016-04-08', '2016-04-06',
        '2016-04-09', '2016-04-12', '2016-04-16', '2016-04-17',
        '2016-04-27', '2016-04-14', '2016-04-18', '2016-04-21',
        '2016-04-19', '2016-04-20', '2016-04-10', '2016-04-13',
        '2016-04-11', '2016-04-07', '2016-04-15', '2016-04-22',
        '2016-04-23', '2016-04-26', '2016-04-28', '2016-04-24',
        '2016-04-25', '2016-04-29', '2016-04-30', '2016-05-01',
        '2016-05-10', '2016-05-02', '2016-05-07', '2016-05-08',
        '2016-05-12', '2016-05-04', '2016-05-06', '2016-05-03',
        '2016-05-09', '2016-05-05', '2016-05-13', '2016-05-14',
        '2016-05-18', '2016-05-19', '2016-05-15', '2016-05-16',
        '2016-05-11', '2016-05-21', '2016-05-22', '2016-05-20',
        '2016-05-24', '2016-05-25', '2016-05-26', '2016-05-23',
        '2016-05-27', '2016-05-17', '2016-05-29', '2016-05-28',
        '2016-05-30', '2016-05-31', '2016-06-01', '2016-06-03',
        '2016-06-08', '2016-06-02', '2016-06-05', '2016-06-06',
        '2016-06-13', '2016-06-07', '2016-06-10', '2016-06-11',
        '2016-06-16', '2016-06-12', '2016-06-14', '2016-06-17',
        '2016-06-04', '2016-06-18', '2016-06-21', '2016-06-09',
        '2016-06-24', '2016-06-20', '2016-06-25', '2016-06-22',
        '2016-06-26', '2016-06-23', '2016-07-01', '2016-06-15',
        '2016-06-28', '2016-07-02', '2016-06-19', '2016-06-27',
        '2016-07-04', '2016-06-30', '2016-07-05', '2016-07-08',
        '2016-07-09', '2016-07-07', '2016-07-12', '2016-06-29',
        '2016-07-10', '2016-07-15', '2016-07-03', '2016-07-16',
        '2016-07-14', '2016-07-18', '2016-07-13', '2016-07-06',
        '2016-07-20', '2016-07-21', '2016-07-23', '2016-07-19',
        '2016-07-11', '2016-07-28', '2016-07-17', '2016-07-25',
        '2016-07-22', '2016-07-29', '2016-08-03', '2016-08-02',
        '2016-08-04', '2016-08-08', '2016-08-10', '2016-08-01',
        '2016-08-06', '2016-03-06', '2016-08-05', '2016-07-26',

In [17]:
df.query('babies > 2 or children > 3 or adults > 4')

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
328,Resort Hotel,1,55,2015,July,29,12,4,10,2,...,No Deposit,8.0,NaN,0,Contract,133.16,0,1,No-Show,2015-07-12
1539,Resort Hotel,1,304,2015,September,36,3,0,3,40,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
1587,Resort Hotel,1,333,2015,September,36,5,2,5,26,...,No Deposit,96.0,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
1643,Resort Hotel,1,336,2015,September,37,7,1,2,50,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-01-18
1752,Resort Hotel,1,340,2015,September,37,12,2,5,26,...,No Deposit,96.0,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
1884,Resort Hotel,1,347,2015,September,38,19,2,5,26,...,No Deposit,96.0,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
1917,Resort Hotel,1,349,2015,September,39,21,1,3,27,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
1962,Resort Hotel,1,352,2015,September,39,24,1,3,27,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
2003,Resort Hotel,1,354,2015,September,39,26,2,5,26,...,No Deposit,96.0,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
2164,Resort Hotel,1,361,2015,October,40,3,2,5,26,...,No Deposit,96.0,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
2173,Resort Hotel,1,338,2015,October,41,4,2,0,55,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
2228,Resort Hotel,1,328,2015,October,41,6,2,5,20,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-09-03
2229,Resort Hotel,1,328,2015,October,41,6,2,5,6,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
2231,Resort Hotel,1,328,2015,October,41,6,2,5,5,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
2417,Resort Hotel,1,334,2015,October,42,12,2,5,10,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
2418,Resort Hotel,1,334,2015,October,42,12,2,5,20,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
2419,Resort Hotel,1,334,2015,October,42,12,2,5,5,...,No Deposit,NaN,NaN,0,Group,0.00,0,0,Canceled,2015-01-02
46619,City Hotel,0,37,2016,January,3,12,0,2,2,...,No Deposit,9.0,NaN,0,Transient,84.45,0,1,Check-Out,2016-01-14
78656,City Hotel,0,11,2015,October,42,11,2,1,1,...,No Deposit,95.0,NaN,0,Transient-Party,95.00,0,0,Check-Out,2015-10-14

In [18]:
df['adults'].value_counts()

adults
2     89680
1     23027
3      6202
0       403
4        62
26        5
5         2
27        2
20        2
40        1
55        1
50        1
6         1
10        1
Name: count, dtype: int64

## Limpieza de datos con Python:
* Detección y eliminación de valores duplicados: Asegúrate de que cada registro en el dataset sea único.
* Verificación y ajuste de tipos de datos: Asegúrate de que todas las columnas coincidan con los tipos de datos indicados en el diccionario de datos.
* Consistencia en valores categóricos: Identifica y corrige cualquier inconsistencia en los valores categóricos (por ejemplo, ‘yes’, ‘Yes’, ‘YES’).
* Manejo de valores faltantes: Identifica y maneja cualquier valor faltante en el dataset. Rellena los valores faltantes con un marcador adecuado para el tipo de dato.
* Detección de datos anómalos: Identifica y corrige cualquier punto de dato inapropiado o inusual (por ejemplo, una estancia de 1000 noches).

## Exploración de datos con Python:
* Visualizaciones exploratorias univariadas: Crea dos tipos diferentes de visualizaciones univariadas. Cada visualización debe incluir una breve interpretación dentro del archivo de código.
* Visualizaciones exploratorias multivariadas: Crea dos tipos diferentes de visualizaciones multivariadas. Cada visualización debe incluir una breve interpretación dentro del archivo de código.

## Análisis adicional:
* Estadísticas descriptivas: Proporciona un resumen estadístico del dataset, incluyendo medidas de tendencia central y dispersión para las variables numéricas.
* Identificación de tendencias: Analiza y discute cualquier tendencia notable que observes en los datos, apoyándote en las visualizaciones y estadísticas descriptivas.